### ISSUE TITLE
Fiery includes 1MB of Firebase Dependencies; no jsnext build for tree shaking in CRA and others

### ISSUE THREAD

**Issue by D1no** [dtinth/fiery#10]
Nice library! However, your build pipeline is confusing. As I see it, you are not emitting a simple jsnext build and also require the whole firebase library. My create-react-app build exploded by 1MB. 

Could you please included a jsnext bundle so treeshaking processors (like webpack in CRA) can make use of the library much better? Potentially set firebase not as a hard dependency and have the user provide the firebase instance at instantiation via a singleton. 

Regarding bundle size: You should always just require the packages you need.

For **Typescript**
```ts
import * as firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
```

For **JavaScript**
```js
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
```

Take a look how to set up rollup with firebase properly here: https://github.com/davideast/firebase-typescript-rollup

I wish I had the time, than I'd provide a PR — but this is better than nothing (I use something else going forward)

**Comment by dtinth** [comment]
@D1no Hello, many thanks for the feedback!

> As I see it, you are not emitting a simple jsnext build

I’m emitting the ESM build (compiled down to ES5 but with ES modules), not sure if that’s the same thing. Example: https://unpkg.com/fiery@0.5.0/esm/index.js

> and also require the whole firebase library. My create-react-app build exploded by 1MB.

Thanks. I didn’t know the whole Firebase library would be this large!

> Take a look how to set up rollup with firebase properly here

Rollup is used to build the UMD version (which is for requiring via script tags), while the ESM version is generated directly using TypeScript compiler (no bundling needed).

I don’t have the time to work on this right now. I will add the “help wanted” label to signify that PRs are welcome.

**Comment by D1no** [comment]
Alright.

> I’m emitting the ESM build (compiled down to ES5 but with ES modules), not sure if that’s the same thing. Example: https://unpkg.com/fiery@0.5.0/esm/index.js

Well just means to ship standard ES6 / ES2018 code with import / export syntax. Otherwise people have ES5 code in their "esnext" project, even though they do not want to target not evergreen browsers. Complicated discussion; look at this: https://twitter.com/dan_abramov/status/1009183876311408641?lang=en
